version: '3'
services:
 react-app:
  build: .
  container_name: appserver1
  restart: always
  volumes:
   - ./data:/data/db
  ports:
   - '9002:3000'
  networks:
   - sample-net
  links:
   - mongo
 mongo:
  container_name: mongo
  image: mongo
  restart: always
  volumes:
   - ./data:/data/db
  ports:
   - '27017:27017'
  networks:
   - sample-net
  environment:
   - MONGO_INITDB_ROOT_USERNAME= "root" 
   - MONGO_INITDB_ROOT_PASSWORD= "rootpassword" 
     

networks:
 sample-net:
  external: true
  
volumes:
 data: 